FROM node:20-alpine AS builder
WORKDIR /app
COPY apps/frontend/admin/package*.json ./
RUN npm install
COPY apps/frontend/admin/ ./
RUN npx vite build

FROM node:20-alpine AS runner
WORKDIR /prod
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 5174
CMD ["serve", "-s", "dist", "-l", "5174"]
