FROM node:20-alpine AS builder
WORKDIR /app
COPY apps/frontend/dashboard/package*.json ./
RUN npm install
COPY apps/frontend/dashboard/ ./
RUN npx vite build

FROM node:20-alpine AS runner
WORKDIR /prod
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
