# api.localhost:8080 → Laravel
server {
    listen 80;
    server_name api.localhost;

    location / {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# dashboard.localhost:8080 → React (Vite)
server {
    listen 80;
    server_name dashboard.localhost;

    location / {
        proxy_pass http://dashboard:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}

# web.localhost:8080 → Next.js
server {
    listen 80;
    server_name web.localhost;

    location / {
        proxy_pass http://web:3000;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }}

# ai.localhost:8080 → Django
server {
    listen 80;
    server_name ai.localhost;

    location / {
        proxy_pass http://ai:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# admin.localhost:8080 → React (Vite) — Admin Dashboard
server {
    listen 80;
    server_name admin.localhost;

    location / {
        proxy_pass http://admin:5174;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}