import type { Metadata } from 'next';
import '../globals.css';
import 'maplibre-gl/dist/maplibre-gl.css';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { getMessages } from 'next-intl/server';
import { Link } from '@/i18n/navigation';
import NextTopLoader from 'nextjs-toploader';
import { getLangDir } from 'rtl-detect';
import NextLoader from 'nextjs-rtl-loader';
import { Button } from '../../components/ui/button';
import { contentFont, headFont } from '@/utils/fonts';
import { Toaster } from '@/components/ui/sonner';
import { QueryProvider } from '@/providers/query-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import { TooltipProvider } from '@/components/ui/tooltip';
import { GoogleMapsProvider } from '@/providers/google-map-provider';
import SessionProvider from '@/providers/session-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as 'en' | 'ar')) {
    notFound();
  }

  const messages = await getMessages();
  const direction = getLangDir(locale);

  return (
    <html
      lang={locale}
      dir={direction}
      suppressHydrationWarning
      className={`${contentFont.variable} ${headFont.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {direction === 'rtl' ? (
          <NextLoader
            zIndex={99999999999999}
            color="var(--primary)"
            height={6}
            showSpinner={true}
          />
        ) : (
          <NextTopLoader
            zIndex={99999999999999}
            color="var(--primary)"
            height={6}
            showSpinner={true}
          />
        )}

        <Toaster position="top-center" richColors />

        <NextIntlClientProvider locale={locale} messages={messages}>
          <QueryProvider>
            <ThemeProvider>
              <GoogleMapsProvider>
                <TooltipProvider>
                  <SessionProvider>{children}</SessionProvider>
                </TooltipProvider>
              </GoogleMapsProvider>
            </ThemeProvider>
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

